// Men's Hostel block codes at VIT Campus (MH prefix dropped)
export const BLOCKS = [
  'A Block',
  'B Block',
  'B Annex',
  'C Block',
  'D Block',
  'D Annex',
  'E Block',
  'F Block',
  'G Block',
  'H Block',
  'J Block',
  'K Block',
  'L Block',
  'M Block',
  'M Annex',
  'N Block',
  'N Annex',
  'P Block',
  'Q Block',
  'R Block',
  'S Block',
  'T Block',
];
